name: Build and deploy Node.js app to Azure Web App - smartmeasure-backend

on:
  push:
    branches:
      - backend-host-azure
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          cd code/smartmeasure-backend
          npm ci

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smartmeasure-backend'
          package: code/smartmeasure-backend